### ISSUE TITLE
No longer seems to work in prepatch

### ISSUE THREAD

**Issue by outlawzgosu** [AvyAddons/AdiBags_Bound#1]
It will work the first time after refresh sometimes, but mostly doesn't add a category anymore like it used to.

**Comment by lucasvienna** [comment]
Thanks for the report, I’ll try and fix it soon.

Right now I’m just waiting on the overhaul from AdiBags to land, since the API should change a bit.

**Comment by lucasvienna** [comment]
@outlawzgosu should be fixed with v1.0.0, can you give it a spin?

**Comment by lucasvienna** [comment]
Closing as resolved in 2850fd94152f401090a4f958287a0a965d2384fa

**Comment by outlawzgosu** [comment]
Sorry for the late reply. Yes it does work like before. This issue seems to be gone. Thank you very much.
