### ISSUE TITLE
[BUG] Broken in latest patch

### ISSUE THREAD

**Issue by derickso** [AvyAddons/AdiBags_Bound#4]
### Description

BoE/BoA items are not being sorted at all

### Addon Version

v10.0.2

### World of Warcraft Flavor

Retail (Dragonflight)

### Tested with only AdiBags_Bound

- [X] Yes
- [ ] No

### Reproduction Steps

Open Adibags
No BoE/BoA filter

### Screenshots

![2022-11-20 20_05_16-World of Warcraft](https://user-images.githubusercontent.com/6112623/202963334-9542ff05-e888-401c-a528-fe3bccbe47e8.png)

**Comment by lucasvienna** [comment]
Fixed in ce487c6ea257da3e6da8377b53da9850dee01fe5, release v1.5.1

![image](https://user-images.githubusercontent.com/1761244/202974081-2e9cfa71-104a-4e12-9cbe-c0b5cd908ed8.png)
